version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8020:8020"
      - "127.0.0.1:8030:8030"
      - "127.0.0.1:8040:8040"
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "gwmainnet:no_eip1898,archive,traces:https://v1.mainnet.godwoken.io/rpc"
      GRAPH_LOG: info
      # RUST_LOG: debug
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: "true"
      ETHEREUM_POLLING_INTERVAL: 30000
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
